#!/bin/bash
set -e



case "$1" in
  configure)
    update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/biglinux-logo-circle/biglinux-logo-circle.plymouth  100
    update-initramfs -u
;;

esac
exit 0
